name: Commit CI

on:
  push:
    branches:
      - '*'
    tags:
      - '![0-9]+.*'
  pull_request:

jobs:
  # linux:
  #   uses: ./.github/workflows/linux-build.yml

  macos:
    uses: ./.github/workflows/macos-build_dr57.yml

  # windows:
  #   uses: ./.github/workflows/windows-build.yml
