name: macOS build
on:
  workflow_call:
    inputs:
      repository:
        default: ${{ github.repository }}
        required: false
        type: string
      build_variant:
        required: false
        type: string
      rime_plugins:
        required: false
        type: string
jobs:
  build:
    runs-on: macos-latest
    env:
      icu4c_version: 72.1
      boost_version: 1.78.0
      BOOST_ROOT: ${{ github.workspace }}/deps/boost_1_78_0
      ICU4C_ROOT: ${{ github.workspace }}/deps/icu4c_72_1
      RIME_PLUGINS: ${{ inputs.rime_plugins }}
    steps:
      - name: Checkout last commit
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository }}
          submodules: recursive

      - name: Configure build environment
        run: |
          echo git_ref_name="$(git describe --always)" >> $GITHUB_ENV

      - name: Configure build variant
        if: contains(inputs.build_variant, '-universal')
        run: |
          echo BUILD_UNIVERSAL=1 >> $GITHUB_ENV

      - name: Cache Icu4c
        id: cache-icu4c
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.ICU4C_ROOT }}.tar.bz2
            ${{ env.ICU4C_ROOT }}/lib
          key: ${{ runner.os }}-icu4c-${{ env.icu4c_version }}

      - name: Extract Icu4c source tarball
        if: steps.cache-icu4c.outputs.cache-hit == 'true'
        run: |
          pushd deps
          tar --bzip2 -xf ${{ env.ICU4C_ROOT }}.tar.bz2
          popd

      - name: Install Icu4c
        if: steps.cache-icu4c.outputs.cache-hit != 'true'
        run: ./install-icu4c.sh

      - name: Cache Boost
        id: cache-boost
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.BOOST_ROOT }}.tar.bz2
            ${{ env.BOOST_ROOT }}/stage
          key: ${{ runner.os }}-boost-${{ env.boost_version }}

      - name: Extract Boost source tarball
        if: steps.cache-boost.outputs.cache-hit == 'true'
        run: |
          pushd deps
          tar --bzip2 -xf ${{ env.BOOST_ROOT }}.tar.bz2
          popd

      - name: Install Boost
        if: steps.cache-boost.outputs.cache-hit != 'true'
        run: ./install-boost.sh

      - name: Check submodules
        run: git submodule > submodule-status

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: |
            bin
            include
            lib
            share
          key: ${{ runner.os }}${{ inputs.build_variant }}-deps-${{ hashFiles('submodule-status') }}

      - name: Build dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: make MACOSX_DEPLOYMENT_TARGET='13.0' xcode/deps

      - name: Install Rime plugins
        run: ./action-install-plugins-macos.sh

      - name: Build and test
        run: make MACOSX_DEPLOYMENT_TARGET='13.0' xcode/test

      - name: Create distributable
        run: |
          make MACOSX_DEPLOYMENT_TARGET='13.0' xcode/dist-with-icu
          tar -cjvf rime-${{ env.git_ref_name }}-${{ runner.os }}.tar.bz2 \
          dist version-info.txt
          tar -cjvf rime-deps-${{ env.git_ref_name }}-${{ runner.os }}.tar.bz2 \
          --exclude '*/.placeholder' \
          bin include lib share

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: |
            rime-${{ env.git_ref_name }}-${{ runner.os }}.tar.bz2
            rime-deps-${{ env.git_ref_name }}-${{ runner.os }}.tar.bz2
